# Generated by Django 4.2.6 on 2023-10-06 08:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=10, verbose_name='Группа')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_first_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('student_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('student_second_name', models.CharField(max_length=20, verbose_name='Отчество')),
                ('students_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_stud.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=100)),
                ('title', models.TextField(max_length=250)),
                ('student_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_stud.students')),
            ],
        ),
    ]
